version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12

    working_directory: /go/src/github.com/tlkamp/mockbob
    environment:
      GO111MODULE: "on"
    steps:
      - checkout
      - run:
          name: Code Coverage
          command: |
            mkdir -p /tmp/artifacts
            go test -covermode=count -coverprofile=count.out ./...
            go tool cover -func=count.out
            go tool cover -html=count.out
            mv coverage.html /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts
      - run:
          name: Build
          command: go build